version: "3"

services:
  report:
    build: .
    image: sigurdht/compile-latex
    volumes:
      - ./report:/data/report:Z
      - ./report_output:/data/report_output:Z
      - ./source_code:/data/source_code:Z
      - ./Report.pdf:/data/Report.pdf:Z
      - ./compile.sh:/data/compile.sh:Z
    working_dir: /data
    command: ./compile.sh
