version: "3"

services:
  report:
    image: blang/latex:ubuntu
    volumes:
      - ./report:/data/report:Z
      - ./report_output:/data/output:Z
      - ./Report.pdf:/data/output/main.pdf:Z
    working_dir: /data/report
    command: pdflatex -shell-escape -output-dir /data/output main.tex
