version: "3"

services:
  report:
    build: .
    image: sigurdht/compile-latex
    volumes:
      - ./report:/data/report:ro
      - ./report_output:/data/report_output:rw
      - ./source_code:/data/source_code:ro
      - ./Report.pdf:/data/Report.pdf:rw
      - ./compile.sh:/data/compile.sh:ro
    command: /data/compile.sh
